name: Upload Release Asset

on:
    push:
        branches: 
            - release


jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.6.1
        with:
          versionSpec: '5.1.x'
          
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:  '3.1.100'
          
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.6.1

      - name: Build with dotnet
        run: |
            dotnet build MedicalFactory --configuration Release /p:Platform=x64
            dotnet build MedicalFactory --configuration Release /p:Platform=x86
      - name: Zip Release
        run: |
            Compress-Archive -Path MedicalFactory\bin\Release\netcoreapp3.0\win-x64 -DestinationPath MedicalFactory-win-x64.zip
            Compress-Archive -Path MedicalFactory\bin\Release\netcoreapp3.0\win-x86 -DestinationPath MedicalFactory-win-x86.zip
        shell: powershell
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.gitversion.outputs.fullSemVer }}
          release_name: Release ${{ steps.gitversion.outputs.fullSemVer }}
          draft: false
          prerelease: false
      - name: Upload Release Asset x64
        id: upload-release-asset-x64 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./MedicalFactory-win-x64.zip
          asset_name: MedicalFactory-win-x64.zip
          asset_content_type: application/zip
      - name: Upload Release Asset x86
        id: upload-release-asset-x86 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./MedicalFactory-win-x86.zip
          asset_name: MedicalFactory-win-x86.zip
          asset_content_type: application/zip
